//
//  FPWorkerListInteractor.swift
//  Cryptorio
//
//  Created by Anak Mirasing on 7/14/17.
//  Copyright (c) 2017 iGROOMGRiM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FPWorkerListBusinessLogic {
  func getWorkers(request: FPWorkerList.GetWorkers.Request)
}

protocol FPWorkerListDataStore {
  var fpWorkers: [FPHTMLWorker]? { get set }
}

class FPWorkerListInteractor: FPWorkerListBusinessLogic, FPWorkerListDataStore {
  var presenter: FPWorkerListPresentationLogic?
  var worker: FPWorkerListWorker?
  var fpWorkers: [FPHTMLWorker]?
  
  // MARK: Get Workers
  
  func getWorkers(request: FPWorkerList.GetWorkers.Request) {
    let response = FPWorkerList.GetWorkers.Response(fpWorkers: fpWorkers)
    presenter?.presentWorkerList(response: response)
  }
}
