//
//  FPWorkerListInteractor.swift
//  Cryptorio
//
//  Created by Anak Mirasing on 7/14/17.
//  Copyright (c) 2017 iGROOMGRiM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FPWorkerListBusinessLogic {
  // Get loaded data from dashboard
  func getWorkers(request: FPWorkerList.GetWorkers.Request)
  
  // Get new data from html page
  func fetchWorkers(request: FPWorkerList.FetchWorkers.Request)
}

protocol FPWorkerListDataStore {
  var fpWorkers: [FPHTMLWorker]? { get set }
}

class FPWorkerListInteractor: FPWorkerListBusinessLogic, FPWorkerListDataStore {
  var presenter: FPWorkerListPresentationLogic?
  var worker: FPWorkerListWorker?
  
  var fpWorkers: [FPHTMLWorker]?

  init() {
    worker = FPWorkerListWorker()
  }
  
  func getWorkers(request: FPWorkerList.GetWorkers.Request) {
    let response = FPWorkerList.GetWorkers.Response(fpWorkers: fpWorkers)
    presenter?.presentWorkerList(response: response)
  }
  
  func fetchWorkers(request: FPWorkerList.FetchWorkers.Request) {
    guard let walletID = worker?.fetchWalletID() else {
      return
    }
    
    worker?.fetchWorkers(walletID: walletID, completion: { [weak self] wks in
      guard let fpWorkers = wks else {
        return
      }
      
      let response = FPWorkerList.GetWorkers.Response(fpWorkers: fpWorkers)
      self?.presenter?.presentWorkerList(response: response)
    })
  }
}
