//
//  FPWorkerListPresenter.swift
//  Cryptorio
//
//  Created by Anak Mirasing on 7/14/17.
//  Copyright (c) 2017 iGROOMGRiM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FPWorkerListPresentationLogic {
  func presentWorkerList(response: FPWorkerList.GetWorkers.Response)
}

class FPWorkerListPresenter: FPWorkerListPresentationLogic {
  weak var viewController: FPWorkerListDisplayLogic?
  
  // MARK: Present workers
  
  func presentWorkerList(response: FPWorkerList.GetWorkers.Response) {
    let viewModel = FPWorkerList.GetWorkers.ViewModel(displayedFPWorkers: response.fpWorkers)
    viewController?.displayWokerList(viewModel: viewModel)
  }
}
