//
//  FPPayoutListPresenter.swift
//  Cryptorio
//
//  Created by Anak Mirasing on 7/15/2560 BE.
//  Copyright (c) 2560 iGROOMGRiM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FPPayoutListPresentationLogic {
  func presentSomething(response: FPPayoutList.Something.Response)
}

class FPPayoutListPresenter: FPPayoutListPresentationLogic {
  weak var viewController: FPPayoutListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: FPPayoutList.Something.Response) {
    let viewModel = FPPayoutList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
