//
//  FPPayoutListPresenter.swift
//  Cryptorio
//
//  Created by Anak Mirasing on 7/15/2560 BE.
//  Copyright (c) 2560 iGROOMGRiM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FPPayoutListPresentationLogic {
  func presentPayoutList(response: FPPayoutList.GetPayouts.Response)
}

class FPPayoutListPresenter: FPPayoutListPresentationLogic {
  weak var viewController: FPPayoutListDisplayLogic?
  
  // MARK: Present payouts
  
  func presentPayoutList(response: FPPayoutList.GetPayouts.Response) {
    let viewModel = FPPayoutList.GetPayouts.ViewModel(displayedFPPayouts: response.fpPayouts)
    viewController?.displayPayoutList(viewModel: viewModel)
  }
}
