//
//  FPPayoutListInteractor.swift
//  Cryptorio
//
//  Created by Anak Mirasing on 7/15/2560 BE.
//  Copyright (c) 2560 iGROOMGRiM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FPPayoutListBusinessLogic {
  func fetchPayouts(request: FPPayoutList.FetchPayouts.Request)
}

protocol FPPayoutListDataStore {
  //var name: String { get set }
}

class FPPayoutListInteractor: FPPayoutListBusinessLogic, FPPayoutListDataStore {
  var presenter: FPPayoutListPresentationLogic?
  var worker: FPPayoutListWorker?
  
  var fpPayouts: [FPHTMLPayout]?
  
  init() {
    worker = FPPayoutListWorker()
  }
  
  func fetchPayouts(request: FPPayoutList.FetchPayouts.Request) {
    guard let walletID = worker?.fetchWalletID() else {
      return
    }
    
    worker?.fetchPayouts(walletID: walletID, completion: { [weak self] pos in
      guard let fpPayouts = pos else {
        return
      }
      
      let response = FPPayoutList.GetPayouts.Response(fpPayouts: fpPayouts)
      self?.presenter?.presentPayoutList(response: response)
    })
  }
}
