//
//  FPPayoutListModels.swift
//  Cryptorio
//
//  Created by Anak Mirasing on 7/15/2560 BE.
//  Copyright (c) 2560 iGROOMGRiM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum FPPayoutList {
  // MARK: Use cases
  
  enum GetPayouts {
    struct Request {
    }
    struct Response {
      var fpPayouts: [FPHTMLPayout]?
    }
    struct ViewModel {
      var displayedFPPayouts: [FPHTMLPayout]?
    }
  }
  
  enum FetchPayouts {
    struct Request {
    }
    struct Response {
      var fpPayouts: [FPHTMLPayout]?
    }
    struct ViewModel {
      var displayedFPPayouts: [FPHTMLPayout]?
    }
  }
}
