//
//  FPDashboardRouter.swift
//  Cryptorio
//
//  Created by Anak Mirasing on 7/11/2560 BE.
//  Copyright (c) 2560 iGROOMGRiM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol FPDashboardRoutingLogic {
  func routeToShowWorkerList(segue: UIStoryboardSegue?)
}

protocol FPDashboardDataPassing {
  var dataStore: FPDashboardDataStore? { get }
}

class FPDashboardRouter: NSObject, FPDashboardRoutingLogic, FPDashboardDataPassing {
  weak var viewController: FPDashboardViewController?
  var dataStore: FPDashboardDataStore?
  
  // MARK: Routing
  func routeToShowWorkerList(segue: UIStoryboardSegue?) {
    guard let segue = segue else {
      return
    }
    
    let destinationVC = segue.destination as! FPWorkerListViewController
    var destinationDS = destinationVC.router!.dataStore!
    passDataToShowWorkerList(source: dataStore!, destination: &destinationDS)
  }
  
  // MARK: Navigation
  
  func navigateToShowWorkerList(source: FPDashboardViewController, destination: FPWorkerListViewController) {
    source.show(destination, sender: nil)
  }
  
  // MARK: Passing data
  
  func passDataToShowWorkerList(source: FPDashboardDataStore, destination: inout FPWorkerListDataStore) {
    destination.fpWorkers = source.fpWokers
  }
}
