//
//  FPDashboardInteractor.swift
//  Cryptorio
//
//  Created by Anak Mirasing on 7/11/2560 BE.
//  Copyright (c) 2560 iGROOMGRiM. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol FPDashboardBusinessLogic {
  func fetchData(request: FPDashboard.RequestData.Request)
  func fetchFPWorkers(request: FPDashboard.RequestWorkers.Request)
}

protocol FPDashboardDataStore {
  var fpData: FPData? { get }
}

class FPDashboardInteractor: FPDashboardBusinessLogic, FPDashboardDataStore {
  var presenter: FPDashboardPresentationLogic?
  var worker: FPDashboardWorker?
  var fpData: FPData?
  
  init() {
    worker = FPDashboardWorker()
  }
  
  func fetchData(request: FPDashboard.RequestData.Request) {
    guard let walletID = worker?.fetchWalletID() else {
      self.presenter?.presentDashboardAddWalletNotification()
      return
    }
    
    worker?.fetchAPIData(walletID: walletID, completion: { [weak self](result) in
      
      switch result {
        case .Success(let fpData):
          let response = FPDashboard.RequestData.Response(flypoolData: fpData)
          self?.presenter?.presentDashboardData(response: response)
          
        case .Failure(let error):
          let errorResponse = FPDashboard.ErrorData.Response(error: error)
          self?.presenter?.presentDashboardErrorMessage(errorResponse: errorResponse)
      }
    })
  }
  
  func fetchFPWorkers(request: FPDashboard.RequestWorkers.Request) {
    guard let walletID = worker?.fetchWalletID() else {
      return
    }
    
    guard let workers = worker?.fetchWorkers(walletID: walletID) else {
      return
    }
    
    let response = FPDashboard.RequestWorkers.Response(workers: workers)
    self.presenter?.presentWorkersData(response: response)
  }
}
